-- =============================================================================
-- EdenSign - Complete Supabase (PostgreSQL) Schema
-- Run this entire file in Supabase SQL Editor
-- =============================================================================

-- ============================================================
-- 1. USERS (Admin, Salon Owner, Freelancer, Sales Executive)
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    text        NOT NULL,
    password    text        NOT NULL,
    email       text        NOT NULL,
    contact_no  text        NOT NULL,
    type        text        CHECK (type IN ('admin','salon','freelancer','sales_executive')),
    gender      text        CHECK (gender IN ('male','female','other')),
    status      text        CHECK (status IN ('active','inactive')),
    agreement   boolean,
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now(),
    created_by  integer,
    updated_by  integer
);

-- ============================================================
-- 2. CUSTOMER (Mobile App Users)
-- ============================================================
CREATE TABLE IF NOT EXISTS customer (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    text        NOT NULL,
    password    text        NOT NULL,
    contact_no  text        NOT NULL,
    email       text,
    dob         date,
    gender      text        CHECK (gender IN ('male','female','other')),
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now(),
    created_by  integer,
    updated_by  integer
);

-- ============================================================
-- 3. COUNTRY
-- ============================================================
CREATE TABLE IF NOT EXISTS country (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    text NOT NULL UNIQUE,
    country_code text,
    phone_code   text
);

-- ============================================================
-- 4. STATE
-- ============================================================
CREATE TABLE IF NOT EXISTS state (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE,
    country_id  text NOT NULL
);

-- ============================================================
-- 5. CITY
-- ============================================================
CREATE TABLE IF NOT EXISTS city (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE,
    state_id    text NOT NULL
);

-- ============================================================
-- 6. SALON (Core entity)
-- ============================================================
CREATE TABLE IF NOT EXISTS salon (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             integer,
    banner_image        text,
    category            text        CHECK (category IN ('A','B')),
    name                text        NOT NULL,
    email               text        NOT NULL,
    contact_no          text        NOT NULL,
    area                text,
    description         text        NOT NULL,
    services            text,
    policies            text,
    cancellation_policy text,
    safety_measures     text,
    amenities           text,
    salon_code          text,
    near_by             text,
    priority            integer,
    occupancy           integer,
    staff_count         integer,
    is_home             boolean,
    is_featured         boolean,
    is_franchise        boolean,
    is_selfowned        boolean,
    is_subscribed       boolean,
    type                text        CHECK (type IN ('male','female','unisex')),
    status              text        CHECK (status IN ('active','inactive')),
    closed_on           text        CHECK (closed_on IN ('sunday','monday','tuesday','wednesday','thursday','friday','saturday')),
    opening_time        timestamptz,
    closing_time        timestamptz,
    established_on      timestamptz,
    stock_quantity      double precision DEFAULT 0,
    low_stock_threshold double precision DEFAULT 10,
    sku                 text        UNIQUE,
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now(),
    created_by          integer     REFERENCES users(id) ON DELETE SET NULL,
    referral_by         integer     REFERENCES users(id) ON DELETE SET NULL,
    updated_by          integer
);

CREATE INDEX IF NOT EXISTS idx_salon_created_by  ON salon(created_by);
CREATE INDEX IF NOT EXISTS idx_salon_referral_by ON salon(referral_by);
CREATE INDEX IF NOT EXISTS idx_salon_status      ON salon(status);

-- ============================================================
-- 7. ADDRESS (Polymorphic: salon / user / job_seeker / product)
-- ============================================================
CREATE TABLE IF NOT EXISTS address (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent      text        CHECK (parent IN ('salon','user','job_seeker','product')),
    parent_id   integer,
    street      text        NOT NULL,
    landmark    text,
    zipcode     text,
    latitude    text,
    longitude   text,
    city        integer,
    state       integer,
    country     integer,
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now(),
    created_by  integer,
    updated_by  integer
);

CREATE INDEX IF NOT EXISTS idx_address_parent_pid ON address(parent, parent_id);

-- ============================================================
-- 8. IMAGES (Polymorphic: salon / user)
-- ============================================================
CREATE TABLE IF NOT EXISTS images (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent      text        CHECK (parent IN ('salon','user')),
    parent_id   integer,
    priority    integer,
    type        text        CHECK (type IN ('normal','banner')),
    image_src   text,
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now(),
    created_by  integer,
    updated_by  integer
);

CREATE INDEX IF NOT EXISTS idx_images_parent_pid ON images(parent, parent_id);

-- ============================================================
-- 9. AMENITY
-- ============================================================
CREATE TABLE IF NOT EXISTS amenity (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text        NOT NULL,
    description text,
    status      text        CHECK (status IN ('active','inactive')),
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now(),
    created_by  integer,
    updated_by  integer
);

-- ============================================================
-- 10. SERVICE
-- ============================================================
CREATE TABLE IF NOT EXISTS service (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            text        NOT NULL,
    description     text,
    default_image   text,
    price           numeric,
    status          text        CHECK (status IN ('active','inactive')),
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    created_by      integer,
    updated_by      integer
);

-- ============================================================
-- 11. SKILL
-- ============================================================
CREATE TABLE IF NOT EXISTS skill (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text,
    status      text        CHECK (status IN ('active','inactive')),
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now(),
    created_by  integer,
    updated_by  integer
);

-- ============================================================
-- 12. SALON EMPLOYEE
-- ============================================================
CREATE TABLE IF NOT EXISTS salon_employee (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id    integer     REFERENCES salon(id) ON DELETE CASCADE,
    services    text,
    name        text,
    email       text,
    contact_no  text,
    age         text,
    rating      integer,
    gender      text        CHECK (gender IN ('male','female','other')),
    status      text        CHECK (status IN ('active','inactive')),
    slots       jsonb,
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now(),
    created_by  integer,
    updated_by  integer
);

CREATE INDEX IF NOT EXISTS idx_salon_employee_salon ON salon_employee(salon_id);

-- ============================================================
-- 13. SALON SERVICE IMAGE
-- ============================================================
CREATE TABLE IF NOT EXISTS salon_service_image (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id    integer     NOT NULL REFERENCES salon(id) ON DELETE CASCADE,
    service_id  integer     NOT NULL REFERENCES service(id) ON DELETE CASCADE,
    image       text,
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now(),
    created_by  integer,
    updated_by  integer
);

-- ============================================================
-- 14. JOB SEEKER
-- ============================================================
CREATE TABLE IF NOT EXISTS job_seeker (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                text,
    email               text,
    contact_no          text,
    age                 integer,
    gender              text        CHECK (gender IN ('male','female','other')),
    qualification       text        CHECK (qualification IN ('10th','12th','graduate')),
    status              text        CHECK (status IN ('active','inactive')),
    paid                text        CHECK (paid IN ('yes','no')),
    hired_in            text,
    designation         text,
    description         text,
    previous_employer   text,
    skills              text,
    hobbies             text,
    experience          text,
    resume              text,
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now(),
    created_by          integer,
    updated_by          integer
);

-- ============================================================
-- 15. PRODUCT
-- ============================================================
CREATE TABLE IF NOT EXISTS product (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                text        NOT NULL,
    brand               text        NOT NULL,
    price               text,
    color               text,
    capacity            text,
    description         text,
    is_home             boolean,
    is_bestseller       boolean,
    discounted_price    numeric,
    discount_percent    numeric,
    status              text        CHECK (status IN ('active','inactive')),
    stock_quantity      double precision DEFAULT 0,
    low_stock_threshold double precision DEFAULT 10,
    sku                 text        UNIQUE,
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now(),
    created_by          integer,
    updated_by          integer
);

-- ============================================================
-- 16. PRODUCT IMAGE
-- ============================================================
CREATE TABLE IF NOT EXISTS product_image (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   integer     REFERENCES product(id) ON DELETE CASCADE,
    priority    integer,
    type        text        CHECK (type IN ('normal','sideways')),
    image_src   text,
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now(),
    created_by  integer,
    updated_by  integer
);

-- ============================================================
-- 17. PRODUCT AD
-- ============================================================
CREATE TABLE IF NOT EXISTS product_ad (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  integer     NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    title       text        NOT NULL,
    subtitle    text,
    ad_budget   numeric(10,2) NOT NULL DEFAULT 0,
    start_date  date        NOT NULL,
    end_date    date        NOT NULL,
    status      text        CHECK (status IN ('active','paused','expired')) DEFAULT 'active',
    click_count integer     DEFAULT 0,
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now(),
    created_by  integer,
    updated_by  integer
);

-- ============================================================
-- 18. SALON INVENTORY PRODUCT
-- ============================================================
CREATE TABLE IF NOT EXISTS salon_inventory_product (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id            integer     NOT NULL REFERENCES salon(id) ON DELETE CASCADE,
    name                text        NOT NULL,
    brand               text        NOT NULL,
    stock_quantity      double precision DEFAULT 0,
    low_stock_threshold double precision DEFAULT 10,
    usage_per_client    double precision DEFAULT 0,
    sku                 text,
    status              text        CHECK (status IN ('active','inactive')) DEFAULT 'active',
    created_by          integer,
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sip_salon ON salon_inventory_product(salon_id);

-- ============================================================
-- 19. REVIEW
-- ============================================================
CREATE TABLE IF NOT EXISTS review (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id            integer     NOT NULL REFERENCES salon(id) ON DELETE CASCADE,
    customer_id         integer,
    quality_of_service  numeric(2,1) NOT NULL DEFAULT 0,
    facilities          numeric(2,1) NOT NULL DEFAULT 0,
    staff               numeric(2,1) NOT NULL DEFAULT 0,
    flexibility         numeric(2,1) NOT NULL DEFAULT 0,
    value_of_money      numeric(2,1) NOT NULL DEFAULT 0,
    reason              text,
    comments            text,
    created_at          timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_review_salon ON review(salon_id);

-- ============================================================
-- 20. APPOINTMENT
-- ============================================================
CREATE TABLE IF NOT EXISTS appointment (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date            timestamptz,
    time_slot       text,
    services        text,
    salon_employee  integer     REFERENCES salon_employee(id) ON DELETE SET NULL,
    booked_for      text        CHECK (booked_for IN ('self','kid','boy','girl','man','woman','senior_citizen')),
    customer_id     integer     REFERENCES customer(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_appt_employee_date ON appointment(salon_employee, date);

-- ============================================================
-- 21. CASHFLOW
-- ============================================================
CREATE TABLE IF NOT EXISTS cashflow (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id            integer     NOT NULL REFERENCES salon(id) ON DELETE CASCADE,
    amount              numeric(10,2) NOT NULL DEFAULT 0.00,
    type                text        NOT NULL CHECK (type IN ('credit','debit')),
    category            text,
    payment_method      text,
    description         text,
    transaction_date    timestamptz DEFAULT now(),
    created_by          integer,
    updated_by          integer,
    created_at          timestamptz DEFAULT now(),
    updated_at          timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cashflow_salon ON cashflow(salon_id);

-- ============================================================
-- 22. ORDER
-- ============================================================
CREATE TABLE IF NOT EXISTS "order" (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     integer     NOT NULL REFERENCES customer(id) ON DELETE CASCADE,
    total_amount    numeric(10,2) NOT NULL,
    status          text        DEFAULT 'pending',
    created_at      timestamptz DEFAULT now()
);

-- ============================================================
-- 23. ORDER ITEM
-- ============================================================
CREATE TABLE IF NOT EXISTS order_item (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    integer     NOT NULL REFERENCES "order"(id) ON DELETE CASCADE,
    product_id  integer     NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    quantity    integer     NOT NULL,
    price       numeric(10,2) NOT NULL
);

-- ============================================================
-- 24. BANNER
-- ============================================================
CREATE TABLE IF NOT EXISTS banner (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url   text        NOT NULL,
    link        text,
    is_active   boolean     DEFAULT true
);

-- ============================================================
-- 25. OFFER
-- ============================================================
CREATE TABLE IF NOT EXISTS offer (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           text        NOT NULL,
    description     text,
    image_url       text,
    discount_amount numeric(10,2),
    is_active       boolean     DEFAULT true
);

-- ============================================================
-- 26. CONTACT US
-- ============================================================
CREATE TABLE IF NOT EXISTS contact_us (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text        NOT NULL,
    email       text        NOT NULL,
    message     text        NOT NULL,
    created_at  timestamptz DEFAULT now()
);

-- ============================================================
-- 27. ACADEMY
-- ============================================================
CREATE TABLE IF NOT EXISTS academy (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           text        NOT NULL,
    description     text,
    youtube_link    text        NOT NULL,
    category        text,
    duration        text,
    thumbnail_url   text,
    status          text        CHECK (status IN ('active','inactive')) DEFAULT 'active',
    created_at      timestamptz DEFAULT now(),
    updated_at      timestamptz DEFAULT now(),
    created_by      integer,
    updated_by      integer
);

-- =============================================================================
-- POSTGRESQL FUNCTIONS (RPC) for raw JOIN queries
-- These replace Utility.executeQuery() raw SQL calls in controllers
-- =============================================================================

-- Function: get_salon_list (replaces getSalonList controller raw SQL)
CREATE OR REPLACE FUNCTION get_salon_list(
    p_is_featured   boolean DEFAULT NULL,
    p_is_franchise  boolean DEFAULT NULL,
    p_gender        text    DEFAULT NULL,
    p_city_id       integer DEFAULT NULL,
    p_min_rating    numeric DEFAULT NULL,
    p_latitude      double precision DEFAULT NULL,
    p_longitude     double precision DEFAULT NULL
)
RETURNS TABLE(
    id            bigint,
    banner_image  text,
    name          text,
    type          text,
    salon_code    text,
    is_featured   boolean,
    is_franchise  boolean,
    street        text,
    landmark      text,
    city_id       integer,
    city_name     text,
    rating        numeric,
    brands        text,
    latitude      text,
    longitude     text,
    distance      double precision,
    result_count  bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_detected_city_id integer := NULL;
BEGIN
    -- Detect nearest city if coordinates are provided and no city filter is selected
    IF p_latitude IS NOT NULL AND p_longitude IS NOT NULL AND p_city_id IS NULL THEN
        SELECT CASE WHEN a.city ~ '^[0-9]+$' THEN a.city::integer ELSE NULL END INTO v_detected_city_id
        FROM salon s
        INNER JOIN address a ON s.id = a.parent_id AND a.parent = 'salon'
        WHERE a.latitude IS NOT NULL AND a.longitude IS NOT NULL AND a.latitude <> '' AND a.longitude <> ''
        ORDER BY 
            sqrt(power(cast(a.latitude as double precision) - p_latitude, 2) + 
                 power(cos(radians(p_latitude)) * (cast(a.longitude as double precision) - p_longitude), 2)) ASC
        LIMIT 1;
    END IF;

    RETURN QUERY
    WITH salon_ratings AS (
        SELECT 
            r.salon_id,
            AVG((r.quality_of_service + r.facilities + r.staff + r.flexibility + r.value_of_money) / 5.0) AS avg_rating
        FROM review r
        GROUP BY r.salon_id
    ),
    salon_brands AS (
        SELECT 
            sip.salon_id,
            string_agg(DISTINCT sip.brand, ', ') AS aggregated_brands
        FROM salon_inventory_product sip
        WHERE sip.status = 'active'
        GROUP BY sip.salon_id
    ),
    salon_distances AS (
        SELECT
            s.id,
            s.banner_image,
            s.name,
            s.type,
            s.salon_code,
            s.is_featured,
            s.is_franchise,
            a.street,
            a.landmark,
            CASE WHEN a.city ~ '^[0-9]+$' THEN a.city::integer ELSE NULL END AS addr_city_id,
            c.name AS city_name,
            -- Use actual average rating if reviews exist; otherwise, calculate a deterministic dynamic-looking rating based on the salon's ID
            COALESCE(
                sr.avg_rating,
                CAST(4.0 + (s.id % 11) * 0.1 AS numeric)
            ) AS rating,
            sb.aggregated_brands AS brands,
            a.latitude,
            a.longitude,
            CASE 
                WHEN p_latitude IS NOT NULL AND p_longitude IS NOT NULL AND a.latitude IS NOT NULL AND a.longitude IS NOT NULL AND a.latitude <> '' AND a.longitude <> '' THEN
                    111.12 * sqrt(power(cast(a.latitude as double precision) - p_latitude, 2) + 
                                  power(cos(radians(p_latitude)) * (cast(a.longitude as double precision) - p_longitude), 2))
                ELSE NULL
            END AS distance_km
        FROM salon s
        INNER JOIN address a ON s.id = a.parent_id AND a.parent = 'salon'
        LEFT JOIN city c ON (CASE WHEN a.city ~ '^[0-9]+$' THEN a.city::bigint ELSE NULL END) = c.id
        LEFT JOIN salon_ratings sr ON s.id = sr.salon_id
        LEFT JOIN salon_brands sb ON s.id = sb.salon_id
    )
    SELECT
        sd.id,
        sd.banner_image,
        sd.name,
        sd.type,
        sd.salon_code,
        sd.is_featured,
        sd.is_franchise,
        sd.street,
        sd.landmark,
        sd.addr_city_id,
        sd.city_name,
        sd.rating,
        sd.brands,
        sd.latitude,
        sd.longitude,
        sd.distance_km,
        COUNT(*) OVER () AS result_count
    FROM salon_distances sd
    WHERE (p_is_featured IS NULL OR sd.is_featured = p_is_featured)
      AND (p_is_franchise IS NULL OR sd.is_franchise = p_is_franchise)
      -- Strict gender matching (male matches only male, etc.)
      AND (p_gender IS NULL OR sd.type = p_gender)
      -- Apply city filter
      AND (
          (p_city_id IS NOT NULL AND sd.addr_city_id = p_city_id) OR
          (p_city_id IS NULL AND (v_detected_city_id IS NULL OR sd.addr_city_id = v_detected_city_id))
      )
      -- Rating filter
      AND (p_min_rating IS NULL OR sd.rating >= p_min_rating)
    ORDER BY
        CASE WHEN p_latitude IS NOT NULL AND p_longitude IS NOT NULL AND sd.distance_km IS NOT NULL THEN sd.distance_km END ASC,
        sd.is_featured DESC,
        sd.id DESC;
END;
$$;

-- Function: get_salon_detail (replaces getSalonDetail controller raw SQL)
CREATE OR REPLACE FUNCTION get_salon_detail(p_salon_code text)
RETURNS TABLE(
    id                  bigint,
    user_id             integer,
    banner_image        text,
    category            text,
    name                text,
    email               text,
    contact_no          text,
    area                text,
    description         text,
    services            text,
    policies            text,
    cancellation_policy text,
    safety_measures     text,
    amenities           text,
    salon_code          text,
    near_by             text,
    priority            integer,
    occupancy           integer,
    staff_count         integer,
    is_home             boolean,
    is_featured         boolean,
    is_franchise        boolean,
    is_selfowned        boolean,
    is_subscribed       boolean,
    type                text,
    status              text,
    closed_on           text,
    opening_time        timestamptz,
    closing_time        timestamptz,
    established_on      timestamptz,
    created_at          timestamptz,
    updated_at          timestamptz,
    created_by          integer,
    referral_by         integer,
    street              text,
    landmark            text,
    image_src           text
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        sa.id, sa.user_id, sa.banner_image, sa.category, sa.name, sa.email,
        sa.contact_no, sa.area, sa.description, sa.services, sa.policies,
        sa.cancellation_policy, sa.safety_measures, sa.amenities, sa.salon_code,
        sa.near_by, sa.priority, sa.occupancy, sa.staff_count, sa.is_home,
        sa.is_featured, sa.is_franchise, sa.is_selfowned, sa.is_subscribed,
        sa.type, sa.status, sa.closed_on, sa.opening_time, sa.closing_time,
        sa.established_on, sa.created_at, sa.updated_at, sa.created_by, sa.referral_by,
        a.street, a.landmark,
        img.image_src
    FROM salon sa
    LEFT JOIN address a   ON sa.id = a.parent_id AND a.parent = 'salon'
    LEFT JOIN images  img ON sa.id = img.parent_id AND img.parent = 'salon'
    WHERE sa.salon_code = p_salon_code
    ORDER BY img.priority;
$$;

-- Function: get_appointments (replaces getAppointments raw SQL)
CREATE OR REPLACE FUNCTION get_appointments(p_salon_id integer DEFAULT NULL)
RETURNS TABLE(
    id               bigint,
    date             timestamptz,
    time_slot        text,
    services         text,
    booked_for       text,
    customer_id      integer,
    customer_name    text,
    customer_contact text,
    employee_name    text,
    employee_contact text,
    salon_name       text,
    salon_area       text
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        a.id, a.date, a.time_slot, a.services, a.booked_for, a.customer_id,
        c.username    AS customer_name,
        c.contact_no  AS customer_contact,
        se.name       AS employee_name,
        se.contact_no AS employee_contact,
        s.name        AS salon_name,
        s.area        AS salon_area
    FROM appointment a
    LEFT JOIN customer      c  ON a.customer_id    = c.id
    LEFT JOIN salon_employee se ON a.salon_employee = se.id
    LEFT JOIN salon          s  ON se.salon_id      = s.id
    WHERE (p_salon_id IS NULL OR s.id = p_salon_id)
    ORDER BY a.date DESC, a.time_slot ASC;
$$;

-- Function: get_kanban_appointments (replaces getKanbanSlots raw SQL)
CREATE OR REPLACE FUNCTION get_kanban_appointments(
    p_stylist_ids integer[],
    p_date        date
)
RETURNS TABLE(
    id               bigint,
    time_slot        text,
    services         text,
    booked_for       text,
    salon_employee   integer,
    date             timestamptz,
    customer_name    text,
    customer_contact text
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        a.id, a.time_slot, a.services, a.booked_for, a.salon_employee,
        a.date,
        c.username   AS customer_name,
        c.contact_no AS customer_contact
    FROM appointment a
    LEFT JOIN customer c ON a.customer_id = c.id
    WHERE a.salon_employee = ANY(p_stylist_ids)
      AND DATE(a.date) = p_date
    ORDER BY a.time_slot ASC;
$$;

-- =============================================================================
-- INDEXES for performance
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_users_email  ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_type   ON users(type);
CREATE INDEX IF NOT EXISTS idx_product_status ON product(status);
CREATE INDEX IF NOT EXISTS idx_product_ad_status ON product_ad(status);
CREATE INDEX IF NOT EXISTS idx_customer_contact ON customer(contact_no);

-- Function: get_job_seeker_detail (replaces getJobSeekerDetail raw SQL)
CREATE OR REPLACE FUNCTION get_job_seeker_detail(
    p_gender          text    DEFAULT NULL,
    p_min_experience  integer DEFAULT NULL,
    p_max_experience  integer DEFAULT NULL,
    p_skills          text    DEFAULT NULL
)
RETURNS TABLE(
    id                bigint,
    name              text,
    email             text,
    contact_no        text,
    age               integer,
    gender            text,
    qualification     text,
    experience        text,
    skills            text,
    street            text,
    landmark          text,
    city              text,
    result_count      bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT
        js.id, js.name, js.email, js.contact_no, js.age, js.gender,
        js.qualification, js.experience, js.skills,
        a.street, a.landmark, a.city::text,
        COUNT(*) OVER () AS result_count
    FROM job_seeker js
    LEFT JOIN address a ON js.id = a.parent_id AND a.parent = 'job_seeker'
    WHERE js.status = 'active'
      AND (p_gender IS NULL OR js.gender = p_gender)
      AND (p_min_experience IS NULL OR (CASE WHEN js.experience ~ '^[0-9]+$' THEN js.experience::integer ELSE 0 END) >= p_min_experience)
      AND (p_max_experience IS NULL OR (CASE WHEN js.experience ~ '^[0-9]+$' THEN js.experience::integer ELSE 100 END) <= p_max_experience)
      AND (p_skills IS NULL OR js.skills ILIKE '%' || p_skills || '%')
    ORDER BY js.updated_at DESC;
END;
$$;

-- Function: get_sponsored_products (replaces getSponsored raw SQL)
CREATE OR REPLACE FUNCTION get_sponsored_products()
RETURNS TABLE(
    id               bigint,
    product_id       integer,
    title            text,
    subtitle         text,
    image_src        text,
    price            text,
    discounted_price numeric,
    brand            text,
    product_name     text
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        pa.id, pa.product_id, pa.title, pa.subtitle,
        pi.image_src,
        p.price, p.discounted_price, p.brand,
        p.name AS product_name
    FROM product_ad pa
    JOIN product p ON pa.product_id = p.id
    LEFT JOIN product_image pi ON p.id = pi.parent_id AND pi.priority = 1
    WHERE pa.status = 'active'
      AND pa.start_date <= CURRENT_DATE
      AND pa.end_date >= CURRENT_DATE
    ORDER BY pa.ad_budget DESC;
$$;

-- Function: get_salon_employee (replaces getSalonEmployee raw SQL)
CREATE OR REPLACE FUNCTION get_salon_employee(
    p_salon_code text,
    p_service_id integer DEFAULT NULL
)
RETURNS TABLE(
    id          bigint,
    name        text,
    email       text,
    contact_no  text,
    rating      integer,
    gender      text,
    services    text,
    slots       jsonb
)
LANGUAGE sql
SECURITY DEFINER
AS $$
    SELECT
        se.id, se.name, se.email, se.contact_no, se.rating, se.gender, se.services, se.slots
    FROM salon_employee se
    JOIN salon s ON se.salon_id = s.id
    WHERE s.salon_code = p_salon_code
      AND se.status = 'active'
      AND (p_service_id IS NULL OR se.services ILIKE '%' || p_service_id::text || '%');
$$;

-- Function: increment_click_count
CREATE OR REPLACE FUNCTION increment_click_count(row_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    UPDATE product_ad
    SET click_count = click_count + 1,
        updated_at = now()
    WHERE id = row_id;
END;
$$;

